### PR TITLE
Fix community bio validation

### LINKED ISSUE #52: [Communities] String properties' length measurements differ between frontend and contract
Certain community metadata string properties that assumed to be valid on frontend considered to be invalid by the contract

Fixed in https://github.com/near/neardevhub-contract/pull/51

## Preview

[Testnet](https://test.near.social/1337hub.testnet/widget/gigs-board.pages.community.configuration?handle=test-test)

### PR DESCRIPTION
**Pull request by akaia-shadowfox**
Fixes #52 

## Preview

[Testnet](https://test.near.social/1337hub.testnet/widget/gigs-board.pages.community.configuration?handle=test-test)

### CODE REVIEW

File: src/community/mod.rs [hunk 1]
```diff
@@ -100,10 +100,7 @@ impl Community {
             panic!("Community description must contain from 6 to 60 characters");
         }
 
-        if self.bio_markdown.is_some()
-            && (self.bio_markdown.as_ref().unwrap().len() < 3
-                || self.bio_markdown.as_ref().unwrap().len() > 200)
-        {
+        if !matches!(self.bio_markdown.to_owned().map_or(0, |text| text.chars().count()), 3..=200) {
```
Comment (frol) [inline src/community/mod.rs]: The same should be applied to other String fields above, I believe.

Comment (akaia-shadowfox) [reply src/community/mod.rs]: Updated!

File: src/community/mod.rs [hunk 2]
```diff
@@ -84,26 +84,23 @@ pub struct CommunityPermissions {
 
 impl Community {
     pub fn validate(&self) {
-        if self.handle.len() < 3 || self.handle.len() > 40 {
+        if self.handle.chars().count() < 3 || self.handle.chars().count() > 40 {
```
Comment (frol) [inline src/community/mod.rs]: Your code might be optimized, but it might also not optimized and then you would have twice than necessary times computing the `.count()`, so I suggest we use `matches!` everywhere:

```suggestion
        if !matches(self.handle.chars().count(),  3..=40) {
```

**Comment by akaia-shadowfox** [comment]
@frol code updated, preview redeployed and tested

**Review by frol — APPROVED** [review]
