### PR TITLE
fix: Removed hardcoded domain name

### LINKED ISSUE #254: Incorrect post link redirect behavior due to hardcoded URL
**Describe the bug**
The post link of a post is hardcoded which produces incorrect redirecting behaviour when users attempt to access the linked post.

**To Reproduce**
1. Go to a profile page for example [this one](https://near.social/mob.near/widget/ProfilePage?accountId=thomasguntenaar.near)
2. Click on `Posted on Devhub`
3. It will redirect to [the wrong post](https://near.social/devgovgigs.near/widget/Post?id=7)

**Expected behavior**
It should redirect to the right post on the right dynamic domain instead of statically redirecting to `near.social`

**Desktop:**
 - OS: Mac
 - Browser Chrome
 - Version 116.0.5845.140

**Additional context**
The problem is part of neardevhub-contract re-posting implementation: [https://github.com/near/neardevhub-contract/blob/main/src/repost.rs#L7](https://github.com/near/neardevhub-contract/blob/main/src/repost.rs#L7)
It should be a relative link instead of hardcoding the domain name. (remove the https://near.social, keep the `/#/`) 
More generic solution with customization is not needed as we will hopefully will move away from cross-posting.

### PR DESCRIPTION
**Pull request by Rishabhraghwendra18**
closes: https://github.com/near/neardevhub-widgets/issues/254

### CODE REVIEW

File: src/repost.rs [hunk 1]
```diff
@@ -5,7 +5,7 @@ use near_sdk::{env, AccountId, Promise};
 
 
 fn repost_internal(post: Post, contract_address: AccountId) -> near_sdk::serde_json::Value {
-    let post_link = format!("https://near.social/#/devgovgigs.near/widget/Post?id={}", post.id);
+    let post_link = format!("/#/devgovgigs.near/widget/Post?id={}", post.id);
```
Comment (akaia-shadowfox) [inline src/repost.rs]: "#" is not required anymore, let's drop it

```suggestion
    let post_link = format!("/devgovgigs.near/widget/Post?id={}", post.id);
```

File: src/repost.rs [hunk 2]
```diff
@@ -81,7 +81,7 @@ mod tests {
         let expected = json!({
             "devgovgigs.near": {
                 "post": {
-                  "main": "{\"type\":\"md\",\"text\":\"@neardevgov.near [Posted on DevHub](https://near.social/#/devgovgigs.near/widget/Post?id=0)\\n## Idea: A call for Zero Knowledge Work Group members!\\nWe are excited to create a more formal Zero Knowledge Work Group (WG) to oversee official decisions on Zero Knowledge proposals. We’re looking for 3-7 experts to participate. Reply to the post if you’re interested in becoming a work group member.\"}"
+                  "main": "{\"type\":\"md\",\"text\":\"@neardevgov.near [Posted on DevHub](/#/devgovgigs.near/widget/Post?id=0)\\n## Idea: A call for Zero Knowledge Work Group members!\\nWe are excited to create a more formal Zero Knowledge Work Group (WG) to oversee official decisions on Zero Knowledge proposals. We’re looking for 3-7 experts to participate. Reply to the post if you’re interested in becoming a work group member.\"}"
```
Comment (akaia-shadowfox) [inline src/repost.rs]: Same here

```suggestion
                  "main": "{\"type\":\"md\",\"text\":\"@neardevgov.near [Posted on DevHub](/devgovgigs.near/widget/Post?id=0)\\n## Idea: A call for Zero Knowledge Work Group members!\\nWe are excited to create a more formal Zero Knowledge Work Group (WG) to oversee official decisions on Zero Knowledge proposals. We’re looking for 3-7 experts to participate. Reply to the post if you’re interested in becoming a work group member.\"}"
```

**Review by akaia-shadowfox — CHANGES_REQUESTED** [review]

**Review by frol — APPROVED** [review]

**Review by akaia-shadowfox — APPROVED** [review]
